### ISSUE TITLE
cant run local test

### ISSUE THREAD

**Issue by aurangzaib-danial** [learn-co-students/traversing-nested-objects-bootcamp-prep-000#2]
if this lesson is just a readme then please mark it as a readme, so its shows completed the lesson

**Comment by samnags** [comment]
Still the case, at least for bootcamp prep track @aturkewi

**Comment by aturkewi** [comment]
Thanks for letting me know!
Also, just a heads up, it's really hard for us to find issues on these _deployed_ copies of labs. The best place to raise issues is on the canonical copies. You can easily get to the correct location but click on the flag icon at the top of the lesson on Learn to raise an issue :)
This issue will be track here: https://github.com/learn-co-curriculum/traversing-nested-objects/issues/14
Closing
